### ISSUE TITLE
Fix en_GB

### ISSUE THREAD

**Issue by afragen** [afragen/git-updater-translations#30]
There seems to be an issue with the en_GB.po file. 

See https://wordpress.org/support/topic/esc_html__-weird-response/

**Comment by afragen** [comment]
I fixed this by simply removing the files as there are no actual translations.

**Comment by monopauly** [comment]
Hi,

I have installed your plugin Github Updater and I am having a problem with the translations not updating. I am receiving the following issue.

Updating translations for GitHub Updater (en_GB)…
Download failed. Not Found

Is there some way to fix this?

Regards

Paul

**Comment by afragen** [comment]
There aren't any actual translations in en_GB so I will be removing those files.
